---
title: "Assignment 1"
date: "2022-10-01"
---

Hello My name is Nihan. I hold my Bachelor's of Science in Electrical and Electronic Engineering from Istanbul University in 2004. I have been working in the telecommunication sector for 18 years, both in the technical and sales and project departments. Now, I am working at "TI Sparkle" as a "Sales Manager". Big data analysis is not used much in the telecommunication sector and the sector has a serious deficit in this regard. By having sufficient knowledge about Big Data Analytics, firstly, I want to provide added value for myself and then use this knowledge in telecommunication sector to benefit both my company and my sector. In R, you can use operators to perform common mathematical operations on numbers.

<https://www.linkedin.com/in/nihan-cinisli-k%C3%B6ksoy-204bb5a2/>

## Math Operator 

The + operator is used to add together two values:
And the - operator is used for subtraction:
The sqrt() function returns the square root of a number:

```{r}
10 + 5
10 - 5
sqrt(16)
```

